### ISSUE TITLE
Automating schedule updates

### ISSUE THREAD

**Issue by austinhuang0131** [steviek/PathWidgetXplat#3]
I'm thinking to use GitHub Actions to automate the generation of schedule.json and schedule_override.json. While I have a draft Python script to generate that, I'm wondering how you usually create these files?

**Comment by steviek** [comment]
It's just the file called `GenerateSchedules.kt`. I'm just running a junit test to print to the console and saving that to the file.

I was just copying and pasting in from the path website, and was only doing this as a stopgap when the live departures API was broken.

Currently, the app doesn't use the schedules unless the live API is broken, but being able to fill in later departures from the schedule would definitely be a nice feature, as long as we can keep the schedule up to date.

Have you found a good source of truth for the schedule that gets holiday updates?

**Comment by austinhuang0131** [comment]
Summary of my current approach:

* When you visit every PATH page, it requests https://www.panynj.gov/content/path/en.model.json which essentially is a list of things to render on *every* page, and *then* uses that to render each page, so the master JSON is used instead of HTML scraping (which doesn't work)
* Essentially I check planned service changes, find every button that says "see schedules," and then follow each link. I can determine the date and then read every schedule posted.
* I have not implemented weekday & weekend, but the approach is similar
